services:
  - type: web
    name: python-flask-app
    plan: free
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:$PORT src.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
